### model
# Replace with the local server path if the model has already been downloaded.
model_name_or_path: Qwen/Qwen3.5-0.8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset_dir: datasets/vqa_rad
dataset: vqa_rad_train
eval_dataset: vqa_rad_test
template: qwen3_5_nothink
cutoff_len: 2048
max_samples: 16
preprocessing_num_workers: 1
dataloader_num_workers: 0
enable_thinking: false

### processor
image_max_pixels: 262144
image_min_pixels: 1024

### output
output_dir: saves/qwen35-0_8b-vqa-rad/full/sft-debug
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: false
fp16: false
ddp_timeout: 180000000

### eval
predict_with_generate: true
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20
